export const styles = {
  joinWrap: {
    minHeight: "100vh",
    background: "#0d0d12",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Sora', 'Segoe UI', sans-serif",
    position: "relative",
    overflow: "hidden",
  },
  joinGlow: {
    position: "absolute",
    width: 500,
    height: 500,
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(124,58,237,0.18) 0%, transparent 70%)",
    top: "50%",
    left: "50%",
    transform: "translate(-50%,-50%)",
    pointerEvents: "none",
  },
  joinCard: {
    background: "#13131f",
    border: "1px solid #252536",
    borderRadius: 20,
    padding: "40px 36px",
    width: "100%",
    maxWidth: 400,
    zIndex: 1,
    boxShadow: "0 24px 80px rgba(0,0,0,0.5)",
  },

  // Mobile join card
  mobileJoinCard: {
    borderRadius: 16,
    padding: "32px 24px",
    margin: "0 16px",
  },
  joinLogo: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 6,
  },
  joinLogoText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: 800,
    letterSpacing: "-0.5px",
  },
  joinSub: {
    color: "#55556a",
    fontSize: 13,
    marginBottom: 28,
  },
  joinForm: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  label: {
    color: "#888",
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  input: {
    background: "#1a1a2a",
    border: "1px solid #2a2a3e",
    borderRadius: 10,
    padding: "11px 14px",
    color: "#e8e8f0",
    fontSize: 14,
    fontFamily: "inherit",
    transition: "border-color 0.2s",
  },
  joinBtn: {
    background: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    color: "#fff",
    padding: "13px",
    borderRadius: 10,
    fontSize: 15,
    fontWeight: 700,
    fontFamily: "inherit",
    marginTop: 4,
    transition: "opacity 0.2s, transform 0.15s",
    boxShadow: "0 4px 24px rgba(124,58,237,0.35)",
  },

  appWrap: {
    display: "flex",
    height: "100vh",
    background: "#0d0d12",
    fontFamily: "'Sora', 'Segoe UI', sans-serif",
    color: "#e8e8f0",
    overflow: "hidden",
    position: "relative",
  },
  menuBtn: {
    display: "none",
    position: "absolute",
    top: 14,
    left: 14,
    zIndex: 100,
    background: "#1e1e2e",
    border: "1px solid #2a2a3e",
    borderRadius: 8,
    padding: "8px 10px",
    cursor: "pointer",
    transition: "background 0.2s, border-color 0.2s",
    boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
  },

  mobileMenuBtn: {
    display: "block",
  },

  mobileSidebar: {
    position: "absolute",
    top: 0,
    left: 0,
    height: "100vh",
    width: "280px",
    zIndex: 99,
    transform: "translateX(-100%)",
    background: "#10101a",
    borderRight: "1px solid #1e1e2e",
    boxShadow: "4px 0 20px rgba(0,0,0,0.3)",
  },

  mobileSidebarOpen: {
    transform: "translateX(0)",
  },

  mobileOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    background: "rgba(0,0,0,0.5)",
    zIndex: 98,
    opacity: 0,
    visibility: "hidden",
    transition: "opacity 0.3s, visibility 0.3s",
  },

  mobileOverlayVisible: {
    opacity: 1,
    visibility: "visible",
  },

  sidebar: {
    width: 240,
    background: "#10101a",
    borderRight: "1px solid #1e1e2e",
    display: "flex",
    flexDirection: "column",
    padding: "0 0 16px",
    flexShrink: 0,
    transition: "transform 0.3s ease",
  },
  sidebarHeader: {
    padding: "16px 16px 12px",
    borderBottom: "1px solid #1e1e2e",
  },
  sidebarLogo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: "#e8e8f0",
    fontWeight: 800,
    fontSize: 15,
    letterSpacing: "-0.3px",
  },
  roomBadge: {
    margin: "14px 12px 6px",
    background: "#1e1e2e",
    borderRadius: 8,
    padding: "8px 12px",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  roomHash: {
    color: "#7C3AED",
    fontWeight: 800,
    fontSize: 16,
  },
  roomName: {
    color: "#c5c5d8",
    fontWeight: 600,
    fontSize: 14,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sectionLabel: {
    color: "#444458",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    padding: "12px 16px 6px",
  },
  userList: {
    flex: 1,
    overflowY: "auto",
    padding: "4px 8px",
  },
  userItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "6px 8px",
    borderRadius: 8,
    cursor: "default",
    transition: "background 0.15s",
  },
  onlineDot: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 9,
    height: 9,
    borderRadius: "50%",
    background: "#6BCB77",
    border: "2px solid #10101a",
  },
  userName: {
    fontSize: 13,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  leaveBtn: {
    margin: "8px 12px 0",
    background: "transparent",
    border: "1px solid #2a2a3e",
    borderRadius: 8,
    color: "#FF6B6B",
    padding: "9px",
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "inherit",
    transition: "background 0.15s",
  },

  chatArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  chatHeader: {
    padding: "14px 20px",
    borderBottom: "1px solid #1e1e2e",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "#0d0d12",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  headerHash: {
    color: "#7C3AED",
    fontWeight: 800,
    fontSize: 18,
  },
  headerRoom: {
    color: "#e8e8f0",
    fontWeight: 700,
    fontSize: 15,
  },
  connDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    display: "inline-block",
  },
  connLabel: {
    color: "#555570",
    fontSize: 12,
  },
  headerCount: {
    color: "#444458",
    fontSize: 13,
  },
  connErrorBar: {
    background: "#2d1620",
    color: "#ff9db6",
    borderBottom: "1px solid #5c2438",
    padding: "8px 14px",
    fontSize: 12,
    fontWeight: 600,
  },

  msgList: {
    flex: 1,
    overflowY: "auto",
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  msgRow: {
    display: "flex",
    alignItems: "flex-end",
    gap: 8,
  },
  msgName: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 3,
    letterSpacing: "0.03em",
  },
  bubble: {
    padding: "10px 14px",
    color: "#e8e8f0",
    fontSize: 14,
    lineHeight: 1.55,
    wordBreak: "break-word",
    boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
  },
  msgTime: {
    fontSize: 10,
    color: "#444458",
    marginTop: 3,
  },
  systemMsg: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    color: "#444458",
    fontSize: 12,
    padding: "2px 0",
  },
  systemDot: {
    width: 4,
    height: 4,
    borderRadius: "50%",
    background: "#444458",
    display: "inline-block",
  },
  typingBubble: {
    background: "#1e1e2e",
    borderRadius: "18px 18px 18px 4px",
    padding: "10px 14px",
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  typingText: {
    color: "#666680",
    fontSize: 12,
    marginRight: 6,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#666680",
    display: "inline-block",
    animation: "blink 1.2s infinite",
  },
  emptyState: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: "60px 0",
  },
  emptyText: {
    color: "#3a3a52",
    fontSize: 14,
    textAlign: "center",
  },

  inputBar: {
    padding: "12px 16px",
    borderTop: "1px solid #1e1e2e",
    display: "flex",
    gap: 10,
    alignItems: "center",
    background: "#0d0d12",
  },
  chatInput: {
    flex: 1,
    background: "#1a1a2a",
    border: "1px solid #2a2a3e",
    borderRadius: 12,
    padding: "11px 16px",
    color: "#e8e8f0",
    fontSize: 14,
    fontFamily: "inherit",
    transition: "border-color 0.2s",
  },
  sendBtn: {
    background: "linear-gradient(135deg, #7C3AED, #5B21B6)",
    width: 42,
    height: 42,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "opacity 0.2s, transform 0.15s",
    boxShadow: "0 4px 16px rgba(124,58,237,0.3)",
  },
};
